;METADATA=(Diff=true, UseCommands=true)
[/Script/UEGame.PrlEnhancedInputConfig]
+m_tarrActionMappings=(ActionName="IA_Ctrl",Key=LeftControl,uChordCode=0)
+m_tarrActionMappings=(ActionName="IA_Test_1",Key=One,uChordCode=1)
+m_tarrActionMappings=(ActionName="IA_Test_1",Key=One,uChordCode=1)
+m_tarrAxisMappings=(AxisName="IA_Test_UpDown",Key=Down,bNegative=True)
+m_tarrAxisMappings=(AxisName="IA_Test_UpDown",Key=Up,bNegative=False)

