;METADATA=(Diff=true, UseCommands=true)
[/Script/UEGame.PrlEnhancedInputConfig]
!m_tarrActionMappings=__ClearArray__
+m_tarrAxisMappings=(AxisName="IA_MoveForward",Key=S,bNegative=True)
+m_tarrAxisMappings=(AxisName="IA_MoveForward",Key=W,bNegative=False)
+m_tarrAxisMappings=(AxisName="IA_MoveRight",Key=A,bNegative=True)
+m_tarrAxisMappings=(AxisName="IA_MoveRight",Key=D,bNegative=False)
+m_tarrAxisMappings=(AxisName="IA_PitchDown",Key=MouseY,bNegative=True)
+m_tarrAxisMappings=(AxisName="IA_YawRight",Key=MouseX,bNegative=False)

